"use client";
import { Questrial } from "next/font/google";
import { usePathname } from "next/navigation";

import "@fonts/css/switzer.css";
import "./globals.css";

import "@fonts/font-awesome.min.css";
import "@css/plugins/bootstrap-grid.css";
import "@css/plugins/swiper.min.css";
import "@css/plugins/magnific-popup.css";

import Preloader from "@/layouts/Preloader";
import "@css/style.css";

const secondary_font = Questrial({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-secondary",
  display: "swap",
  adjustFontFallback: false,
});
// export const metadata = {
//   // title: "Plax - Finance & Fintech React NextJS Template",
//   // description: "Generated by create next app",
//   title: " Template",
//   description: "Generated by create next app",
// };
// by anand
export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en" className={`${secondary_font.variable}`}>
      <body>
        {pathname === "/" ? null : pathname === "/index1" && <Preloader />}
        {/* {children} */}
        sai anand
      </body>
    </html>
  );
}
